### ISSUE TITLE
SuperMarquee doesn't work for Angular components

### ISSUE THREAD

**Issue by EdLichtman** [superplug-in/supermarquee#2]
Hi all, I just got the latest version of Angular 

```
 ng version

     _                      _                 ____ _     ___
    / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
   / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
  / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
 /_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
                |___/


Angular CLI: 17.0.6
Node: 20.10.0
Package Manager: npm 10.2.3
OS: win32 x64

Angular: 17.0.6
... animations, cli, common, compiler, compiler-cli, core, forms
... platform-browser, platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1700.6
@angular-devkit/build-angular   17.0.6
@angular-devkit/core            17.0.6
@angular-devkit/schematics      17.0.6
@schematics/angular             17.0.6
rxjs                            7.8.1
typescript                      5.2.2
zone.js                         0.14.2
```

And I downloaded the latest version of SuperMarquee for a personal project to evaluate it. It doesn't seem to work. I thought maybe it was a "Standalone Components" issue, but it seems to be a problem even if I use a Module entry point instead of a Standalone Component.

However, I think I found the culprit.

The error is:

```
"Failed to construct 'CustomElement': The result must not have children" 
```

I uninstalled the package, took the vanillaJS for SuperMarqueeWC.js, and I moved everything that's in the constructor into the "connectedCallback" function and now it works. 

I don't know enough about the code to know whether solving it in this way will not open up other defects, so I'm leaving that to you.

**Comment by benny00100** [comment]
Hi,
thanks for your report and sorry for the inconvenience. 
Currently, we are working on a brand new version of SuperMarquee which will be released next year (source is not publically available atm). Unfortunately, that's why we cannot provide a fix right now.
Please use the workaround you mentioned for now.
