### ISSUE TITLE
Super Bad perfomance

### ISSUE THREAD

**Issue by alvarindev** [superplug-in/supermarquee#3]
Bad perfomance when multiple animations are in the same page. Animations like GSAP or simple CSS gets laggy even if there are an iframe close to the marquee

**Comment by benny00100** [comment]
@alvarindev 
Thanks for your feedback. 

Could you provide a working example which showcases the performance issue?

**Comment by alvarindev** [comment]
I've detected that when there are some iframes (like youtube, vimeo) in the same page the perfomance drops but I can confirm that this issue is due to the iframe and not the marquee, also I feel some perfomance issues when I use some shadow mask to hide the text inlet/outlet. So I close this!
